``` 1.	create an array with the values from 0 .. 23. And Check its attributes.
 Then Reshape it as 2*12,3*8, 4*6,; 2*2*6, 2*4*3,3*4*2,.... and check its attributes.
 ```

In [50]:
import numpy as np    
# Creation array
arr1=np.arange(start=0,stop=24)
arr1      # to Check attributes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize) 
print(arr1.ndim)
print(arr1.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
24
4
1
int32


In [52]:
# To reshape
arr1=arr1.reshape(2,12)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [53]:
# To reshape
arr1=arr1.reshape(3,8)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [54]:
# To reshape
arr1=arr1.reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
# To reshape
arr1=arr1.reshape(2,2,6)
arr1

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [56]:
# To reshape
arr1=arr1.reshape(2,4,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [57]:
# To reshape
arr1=arr1.reshape(3,4,2)
arr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

```	2. Apply a user defined function using vectorize to get the maximum of two arrays
Example : Array1 =  [5,7,9,8,6,4,5]
	     Array2 = [6,3,4,8,9,7,1]
     Output : [6,7,9,8,9,7,5]
```

In [58]:
def user_fn_1(x):
    return(x*x+2*x+12)
def user_fn_2(x):
    return(x*x*x+5*x-5)
cal_1=np.vectorize(user_fn_1)
cal_2=np.vectorize(user_fn_2)
arr1=cal_1([1,2,3,4])
arr2=cal_2([1,2,3,4])
print("arr1=",arr1)
print("arr2=",arr2)

arr1= [15 20 27 36]
arr2= [ 1 13 37 79]


In [59]:
arr3=np.vstack((arr1,arr2))
print(arr3)

[[15 20 27 36]
 [ 1 13 37 79]]


In [60]:
arr3.reshape(2,4)

array([[15, 20, 27, 36],
       [ 1, 13, 37, 79]])

In [61]:
# To find maximum
np.maximum([arr1],[arr2])

array([[15, 20, 37, 79]])

In [62]:
# To find minuimum
np.minimum([arr1],[arr2])

array([[ 1, 13, 27, 36]])

```
3.	Write a Numpy program to generate six random integers between 10 and 30
```

In [63]:
#Fixed value
a=np.linspace(10,30,6)
a

array([10., 14., 18., 22., 26., 30.])

In [64]:
#Random integer
from numpy import random
a=random.randint(10,30,6)
a

array([12, 25, 25, 12, 16, 28])

```
4.	Get all the items between 5 and 10 from Array A.
A = np.array([2,6,1,9,10,3,27])
```

In [65]:
import numpy as np
a=np.array([2,6,1,9,10,3,27])
#list(filter(lambda x : x>5 and x<10,[2,6,1,9,10,3,27]))
print("Values greater than 5 and less than 10 is: ",a[(a>5) & (a<10)])

Values greater than 5 and less than 10 is:  [6 9]


```
5.	Extract all odd numbers from the array.
```

In [66]:
print("",a[a%2!=0])

 [ 1  9  3 27]
