In [1]:
def square(x):
    return x*x

def cube(x):
    return x*square(x)
print(square(5))
print(cube(5))

25
125


### Anonymous function or lambda function
1. Lambda functions
2. Single line function:
### syntax
```
lambda arg list:statement
```

In [2]:
(lambda x:x*x)(5)

25

In [3]:
(lambda x,y:x*y)(10,20)

200

In [4]:
s=lambda x:x*x
s(5)

25

In [5]:
s

<function __main__.<lambda>(x)>

### map(), filter() and reduce()

### map()
```
map(function,Iterable obj)
```

In [6]:
map(lambda x:x**3,[1,2,3,4,5])

In [7]:
list(map(lambda x:x**3,[1,2,3,4,5]))

[1, 8, 27, 64, 125]

In [11]:
# All the element of list raise to power 3 
#Traditional ways
list1=[1,2,3,4,5]
list2=[]
for i in list1:
    list2.append(i**3)
list2

[1, 8, 27, 64, 125]

In [15]:
def add(x,y):
    return x+y
list(map(add,[10,20,30],[10,50,20]))

[20, 70, 50]

In [18]:
list(map(len,("chitta")))

[1, 1, 1, 1, 1, 1]

In [22]:
# Accept multiple value from the user using single input()
# Three integer "10,20,30" -->["10","20","30"]
a,b,c=list(map(int,input().split()))
print(a+b+c)

10 20 30
60


In [23]:
#unpacking 
x,y,z=[100,200,300]

In [24]:
x

100

In [25]:
y

200

In [26]:
z

300

### Filter():
filter(func,interable)

In [27]:
filter(lambda x : x%2==0,[1,2,3,4,5,6,7,8,9])

In [28]:
list(filter(lambda x : x%2==0,[1,2,3,4,5,6,7,8,9]))

[2, 4, 6, 8]

In [30]:
list(map(lambda x : x%2==0,[1,2,3,4,5,6,7,8,10,9]))

[False, True, False, True, False, True, False, True, True, False]

### reduce():

In [31]:
from functools import reduce
reduce(lambda x,y :x+y,[1,2,3,4,5,6,7,8,9,10])

55

In [32]:
from functools import reduce
reduce(lambda x,y :x*y,[1,2,3,4,5,6,7,8,9,10])

3628800

In [35]:
from functools import reduce
reduce(lambda x,y :x/y,[1,2,3,4,5,6,7,8,9,10])

2.7557319223985894e-07

### enumerate()

In [36]:
enumerate([10,20,30,40,50])

In [37]:
list(enumerate([10,20,30,40,50]))

[(0, 10), (1, 20), (2, 30), (3, 40), (4, 50)]

In [40]:
for index,value in enumerate([10,20,30,40,50]):
    print(index,value)

0 10
1 20
2 30
3 40
4 50


In [42]:
for index,value in enumerate([10,20,30,40,50],100):
    print(index,value)

100 10
101 20
102 30
103 40
104 50


### zip():

In [43]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
for x,y in zip(list1,list2):
    print(x+y)

7
9
11
13
15


### Idiomatic programming

In [48]:
# List comprehension
list1=[1,2,3,4,5]
list2=[6,7,8,9,10,11,12]
list3=[]
for x,y in zip(list1,list2):
    list3.append(x+y)
list3

[7, 9, 11, 13, 15]

In [49]:
list4=[x+y for x,y in zip(list1,list2)]
list4

[7, 9, 11, 13, 15]

In [51]:
## Extracting even number from the list using list comprehension
list2=[6,7,8,9,10,11,12]
list6=[i for i in list2 if i%2==0]
list6

[6, 8, 10, 12]

In [52]:
#swapping two numbers
a=20
b=30
print("Before swapping a and b values are: ",a,b)
a,b=b,a
print("After swapping a and b values are: ",a,b)

Before swapping a and b values are:  20 30
After swapping a and b values are:  30 20


In [56]:
#chained comparison
a=20
b=30
c=40
if a<b and b<c:
    pass              # to write empty block ie when u dont write any statement
if a<b<c:
    pass

print(" a is smaller")

 a is smaller


In [57]:
#Ternary operator
print("a is smaller ") if a<b else print("b is smaller")

a is smaller 


In [61]:
#Using in operator 
letter="absecge"
if letter=="a" or letter=="e" or letter="i" or letter="o" or letter ="u":
    pass
if letter in ['a','e','i','o','u']:
    pass
if letter in "aeiou":
    pass

SyntaxError: invalid syntax (<ipython-input-61-fa3de2086db0>, line 3)

In [60]:
#multiple assignment
x=10
y=10
z=10
x=y=z=10
print(x,y,z)

10 10 10


#### Buit-in package (or) module
1. using import
2. using alias names
3. using from and import keywords

In [62]:
help("math")

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

In [68]:
import math
print(math.sqrt(16))
print(math.factorial(5))
print(math.sin(45))
print(math.ceil(12.345))
print(math.floor(12.345))

4.0
120
0.8509035245341184
13
12


In [69]:
import math as m   # here alias name is used
print(m.sqrt(16))
print(m.factorial(5))
print(m.sin(45))
print(math.ceil(12.345))
print(math.floor(12.345))

4.0
120
0.8509035245341184
13
12


In [71]:
from math import *
print(sqrt(16))
print(factorial(5))
print(sin(45))
print(ceil(12.345))
print(floor(12.345))

4.0
120
0.8509035245341184
13
12


### datetime

In [74]:
import datetime
x=datetime.datetime.now()
print(x)

2020-08-14 12:50:19.160199


In [76]:
y=2020
m=7
d=19
y=datetime.datetime(y,m,d)
print(y)

2020-07-19 00:00:00


#### Array creation

In [6]:
# Create an array out List
list1=[2,4,5,7,8]
type(list1)
list1

[2, 4, 5, 7, 8]

In [10]:
# Create an array out List
# Importing numpy library
import numpy as np    # np is used as numpy
arr1=np.array(list1)
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([2, 4, 5, 7, 8])

In [22]:
#Using arange to create an array of 2 D
#arange -->similar to range(start,stop) where stop value is not included
# arange(start,stop,step)--->default start value is zero
arr2=np.arange(10)   # arrange(start,stop)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr3=np.arange(start=1,stop=10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr3=np.arange(start=1,stop=10,step=2)
arr3

array([1, 3, 5, 7, 9])

In [23]:
#Attributes
print(arr2)
arr2.ndim

[0 1 2 3 4 5 6 7 8 9]


1

In [26]:
#reshape--> to the new dimension; 5*2 or 2*5
arr2=arr2.reshape(5,2)
print(arr2.ndim)
print(arr2)

2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
#Array Attributes
print(arr1)
print(arr1.shape)  # returns no. of rows and column
print(arr1.size)   # totl number of elementd in the array
print(arr1.itemsize) # returns the number of bytes to store the elements
print(arr1.dtype)   # data type of the array

[2 4 5 7 8]
(5,)
5
4
int32


In [29]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
# Indexing 
arr2[3][1]

7

In [38]:
#sub-array witj rows indices 0,1,2
arr2[:3]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
#sub-array with rows indices 0,1,2
print(arr2)
print(arr2[:,1])  # here we want to find the all rows of first column


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 3 5 7 9]


In [51]:
#linspace-->Linearly spaced valued in an interval
a=np.linspace(start=1,stop=10,num=12)
print(a)
a

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [54]:
#use arange and reshape in a single line
b=np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
#Convert any n-D array to 1D array--->ravel
c=b.ravel()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
print(b)
b.min()
b.min()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


0

In [61]:
#argmin()-->index of the minimum value to be returned
b.argmin()

0

In [65]:
print(a)
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
1.0
0
10.0
11


In [68]:
print(a.sum())  # returns the sum of all the elements
np.sqrt(a)

66.0


array([1.        , 1.34839972, 1.62368828, 1.85864075, 2.06705764,
       2.2563043 , 2.43086217, 2.59369866, 2.74689908, 2.89199522,
       3.03015151, 3.16227766])

#### Stacking Arrays

In [69]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)  # both should should match 
print(a)
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [70]:
# hstack-->horizontal stacking
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [72]:
# vstake --> vertical; stacking
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [73]:
# vstake --> vertical; stacking
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [74]:
a = np.arange(8).reshape(2,4)
b = np.arange(2).reshape(2,1)
np.hstack([a,b])

array([[0, 1, 2, 3, 0],
       [4, 5, 6, 7, 1]])

## Apply User-defined Functions

In [75]:
# Creating a function
def calculate(x):
    return x*x-5

In [77]:
cal=np.vectorize(calculate)
cal([1,2,3,4])

array([-4, -1,  4, 11])

In [78]:
print(b)
cal(b)

[[0]
 [1]]


array([[-5],
       [-4]])

In [ ]:
# Random Module from Numpy

In [28]:
from numpy import random
a=random.randint(10)
a

5

In [12]:
import numpy
from numpy import random
r=numpy.random.RandomState(1)   # same output 
a=r.rand()   # value between 0 to 1
print(a)
numpy.round(a, decimals=4)

0.417022004702574


0.417

In [17]:
a=random.randint(100)    # returns random integer in the specified range
arr=random.randint(10,size=(2,2))
arr

array([[6, 8],
       [1, 1]])

In [20]:
# choice
random.choice(arr.ravel())

8

In [121]:
random.seed(10)
random.choice([1,2,3,4,5],size=(2,2))

array([[2, 5],
       [1, 2]])

In [18]:
def a(b):

    b = b + [5]

c = [1, 2, 3, 4]

a(c)

print(len(c))



4


In [19]:
What is the output of the code shown below?

def f1():

    x=100

    print(x)

x=+1

f1()

Object `below` not found.
100


In [124]:
result = lambda x: x * x


print(result(5))

25


In [125]:
str1 = "Python 2345";

str2 = "12345"

print(str1.isdigit())


print(str2.isalnum())



False
True


In [126]:
for num in range(2,-5,-1):

      print(num, end=", ")

2, 1, 0, -1, -2, -3, -4, 

In [137]:
 a="abc"
 b="xyz"
 c = a-b
print(c)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [132]:
dict1 = {"name":"a","rollno":123,"name":"b"}

print(dict1["name"])

b


In [133]:
a={}

a[2]=1

a[1]=[2,3,4]

print(a[1][1])

3


In [135]:
ord("a")

97